from .persona import Persona 
from .jefe import Jefe
from .departamento import Departamento
from .director import Director
from .docente import Docente
from .noDocente import NoDocente
from .resolucion import Resolucion
from .jefeDepartamento import JefeDepartamento
from .area import Area
from .asignatura import Asignatura
from .asignaturaCarrera import AsignaturaCarrera
from .asignaturaDocente import AsignaturaDocente
from .carrera import Carrera
from .directorCarrera import DirectorCarrera
