# Generated by Django 5.1.1 on 2024-10-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('codigo', models.CharField(max_length=45)),
                ('nombre', models.CharField(max_length=150)),
                ('modulo', models.CharField(max_length=45)),
                ('programa', models.CharField(blank=True, max_length=45, null=True)),
                ('tipo', models.CharField(max_length=11)),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='AsignaturaCarrera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'AsignaturaCarrera',
                'verbose_name_plural': 'AsignaturaCarreras',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AsignaturaDocente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('condicion', models.CharField(max_length=11)),
                ('cargo', models.CharField(max_length=20)),
                ('dedicacion', models.CharField(max_length=9)),
                ('fecha_de_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_de_vencimiento', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField()),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'AsignaturaDocente',
                'verbose_name_plural': 'AsignaturaDocentes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(max_length=8)),
                ('planestudio', models.CharField(max_length=150)),
                ('sitio', models.CharField(blank=True, max_length=245, null=True)),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=45, null=True)),
                ('estado', models.CharField(max_length=1)),
                ('interno', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'Director',
                'verbose_name_plural': 'Directores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DirectorCarrera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('fecha_de_inicio', models.DateTimeField()),
                ('fecha_de_fin', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField()),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'Director Carrera',
                'verbose_name_plural': 'Directores Carrera',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docente',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Jefe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'Jefe',
                'verbose_name_plural': 'Jefes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='JefeDepartamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('fecha_de_inicio', models.DateTimeField()),
                ('fecha_de_fin', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField()),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'JefeDepartamento',
                'verbose_name_plural': 'Jefes Departamentos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NoDocente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'NoDocente',
                'verbose_name_plural': 'NoDocente',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('nombre', models.CharField()),
                ('apellido', models.CharField()),
                ('telefono', models.CharField()),
                ('dni', models.CharField()),
                ('estado', models.CharField(max_length=1)),
                ('email', models.CharField(blank=True, null=True)),
                ('interno', models.IntegerField()),
                ('legajo', models.CharField(blank=True, null=True)),
                ('titulo', models.CharField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Resolucion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('nexpediente', models.CharField(max_length=100)),
                ('nresolucion', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=17)),
                ('adjunto', models.CharField(max_length=256)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField()),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'Resolucion',
                'verbose_name_plural': 'Resoluciones',
                'ordering': ['nexpediente', 'nresolucion'],
            },
        ),
    ]
