# Generated by Django 4.2.1 on 2024-06-03 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='direccion_ip',
        ),
    ]
