# Generated by Django 5.1.1 on 2024-10-01 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='actualizado_por',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='area',
            name='creado_por',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='actualizado_por',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentos.area'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='creado_por',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='asignaturacarrera',
            name='actualizado_por',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='asignaturacarrera',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentos.asignatura'),
        ),
        migrations.AddField(
            model_name='asignaturacarrera',
            name='creado_por',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='asignaturadocente',
            name='actualizado_por',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='asignaturadocente',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentos.asignatura'),
        ),
        migrations.AddField(
            model_name='asignaturadocente',
            name='creado_por',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='actualizado_por',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='creado_por',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='asignaturacarrera',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentos.carrera'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='actualizado_por',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='creado_por',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentos.departamento'),
        ),
        migrations.AddField(
            model_name='area',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentos.departamento'),
        ),
        migrations.AddField(
            model_name='director',
            name='actualizado_por',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='director',
            name='creado_por',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='directorcarrera',
            name='actualizado_por',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='directorcarrera',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentos.carrera'),
        ),
        migrations.AddField(
            model_name='directorcarrera',
            name='creado_por',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='directorcarrera',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentos.director'),
        ),
        migrations.AddField(
            model_name='docente',
            name='actualizado_por',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='docente',
            name='creado_por',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='asignaturadocente',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentos.docente'),
        ),
        migrations.AddField(
            model_name='jefe',
            name='actualizado_por',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='jefe',
            name='creado_por',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='jefedepartamento',
            name='actualizado_por',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='jefedepartamento',
            name='creado_por',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='jefedepartamento',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentos.departamento'),
        ),
        migrations.AddField(
            model_name='jefedepartamento',
            name='jefe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentos.jefe'),
        ),
        migrations.AddField(
            model_name='nodocente',
            name='actualizado_por',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='nodocente',
            name='creado_por',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='persona',
            name='actualizado_por',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='persona',
            name='creado_por',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='nodocente',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='departamentos.persona'),
        ),
        migrations.AddField(
            model_name='jefe',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='departamentos.persona'),
        ),
        migrations.AddField(
            model_name='docente',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='departamentos.persona'),
        ),
        migrations.AddField(
            model_name='director',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='departamentos.persona'),
        ),
        migrations.AddField(
            model_name='resolucion',
            name='actualizado_por',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='resolucion',
            name='creado_por',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='jefedepartamento',
            name='resolucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentos.resolucion'),
        ),
        migrations.AddField(
            model_name='directorcarrera',
            name='resolucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentos.resolucion'),
        ),
        migrations.AddField(
            model_name='asignaturadocente',
            name='resolucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentos.resolucion'),
        ),
        migrations.AddConstraint(
            model_name='asignatura',
            constraint=models.UniqueConstraint(fields=('codigo',), name='ux_codigo_Asignatura'),
        ),
        migrations.AddConstraint(
            model_name='area',
            constraint=models.UniqueConstraint(fields=('nombre',), name='ux_nombre_area'),
        ),
        migrations.AddConstraint(
            model_name='persona',
            constraint=models.UniqueConstraint(fields=('dni',), name='ux_dni_personas'),
        ),
    ]
