# Generated by Django 4.2.1 on 2024-06-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_remove_persona_direccion_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='dni',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(),
        ),
    ]
