# Generated by Django 4.2.1 on 2024-06-03 23:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departamentos', '0003_alter_persona_dni_alter_persona_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jefe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(max_length=1)),
                ('actualizado_por', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('creado_por', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='departamentos.persona')),
            ],
            options={
                'verbose_name': 'Jefe',
                'verbose_name_plural': 'Jefes',
                'ordering': ['id'],
            },
        ),
    ]
