# Generated by Django 5.1.1 on 2024-12-10 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0003_alter_persona_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='interno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
