# Generated by Django 4.2.1 on 2024-06-07 01:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departamentos', '0004_jefe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=45, null=True)),
                ('estado', models.CharField(max_length=1)),
                ('interno', models.CharField(blank=True, max_length=45, null=True)),
                ('actualizado_por', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('creado_por', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Resolucion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('nexpediente', models.CharField(max_length=100)),
                ('nresolucion', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=17)),
                ('adjunto', models.CharField(max_length=256)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fechadecarga', models.DateTimeField()),
                ('fecha', models.DateTimeField()),
                ('estado', models.CharField(max_length=1)),
                ('actualizado_por', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('creado_por', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Resolucion',
                'verbose_name_plural': 'Resoluciones',
                'ordering': ['nexpediente', 'nresolucion'],
            },
        ),
        migrations.CreateModel(
            name='NoDocente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(max_length=1)),
                ('actualizado_por', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('creado_por', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='departamentos.persona')),
            ],
            options={
                'verbose_name': 'NoDocente',
                'verbose_name_plural': 'NoDocente',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='JefeDepartamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('fecha_de_inicio', models.DateTimeField()),
                ('fecha_de_fin', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField()),
                ('estado', models.CharField(max_length=1)),
                ('actualizado_por', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('creado_por', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentos.departamento')),
                ('jefe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentos.jefe')),
                ('resolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentos.resolucion')),
            ],
            options={
                'verbose_name': 'JefeDepartamento',
                'verbose_name_plural': 'Jefes Departamentos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(max_length=1)),
                ('actualizado_por', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('creado_por', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='departamentos.persona')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docente',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(max_length=1)),
                ('actualizado_por', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('creado_por', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='departamentos.persona')),
            ],
            options={
                'verbose_name': 'Director',
                'verbose_name_plural': 'Directores',
                'ordering': ['id'],
            },
        ),
    ]
