# Generated by Django 4.2.1 on 2024-06-10 22:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departamentos', '0005_departamento_resolucion_nodocente_jefedepartamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=1)),
                ('actualizado_por', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('creado_por', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentos.departamento')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('codigo', models.CharField(max_length=45)),
                ('nombre', models.CharField(max_length=150)),
                ('modulo', models.CharField(max_length=45)),
                ('programa', models.CharField(blank=True, max_length=45, null=True)),
                ('tipo', models.CharField(max_length=11)),
                ('estado', models.CharField(max_length=1)),
                ('actualizado_por', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentos.area')),
                ('creado_por', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentos.departamento')),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(max_length=8)),
                ('planestudio', models.CharField(max_length=150)),
                ('sitio', models.CharField(blank=True, max_length=245, null=True)),
                ('estado', models.CharField(max_length=1)),
                ('actualizado_por', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('creado_por', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DirectorCarrera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('fecha_de_inicio', models.DateTimeField()),
                ('fecha_de_fin', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField()),
                ('estado', models.CharField(max_length=1)),
                ('actualizado_por', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentos.carrera')),
                ('creado_por', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentos.director')),
                ('resolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentos.resolucion')),
            ],
            options={
                'verbose_name': 'Director Carrera',
                'verbose_name_plural': 'Directores Carrera',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AsignaturaDocente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('condicion', models.CharField(max_length=11)),
                ('cargo', models.CharField(max_length=20)),
                ('dedicacion', models.CharField(max_length=9)),
                ('fecha_de_creacion', models.DateTimeField()),
                ('fecha_de_modificacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_de_vencimiento', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField()),
                ('estado', models.CharField(max_length=1)),
                ('actualizado_por', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentos.asignatura')),
                ('creado_por', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentos.docente')),
                ('resolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentos.resolucion')),
            ],
            options={
                'verbose_name': 'AsignaturaDocente',
                'verbose_name_plural': 'AsignaturaDocentes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AsignaturaCarrera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('estado', models.CharField(max_length=1)),
                ('fecha_de_creacion', models.DateTimeField()),
                ('fecha_de_modificacion', models.DateTimeField(blank=True, null=True)),
                ('actualizado_por', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentos.asignatura')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentos.carrera')),
                ('creado_por', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'AsignaturaCarrera',
                'verbose_name_plural': 'AsignaturaCarreras',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='asignatura',
            constraint=models.UniqueConstraint(fields=('codigo',), name='ux_codigo_Asignatura'),
        ),
        migrations.AddConstraint(
            model_name='area',
            constraint=models.UniqueConstraint(fields=('nombre',), name='ux_nombre_area'),
        ),
    ]
