# Generated by Django 4.2.1 on 2024-06-10 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0006_area_asignatura_carrera_directorcarrera_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignaturacarrera',
            name='fecha_de_creacion',
        ),
        migrations.RemoveField(
            model_name='asignaturacarrera',
            name='fecha_de_modificacion',
        ),
        migrations.RemoveField(
            model_name='asignaturadocente',
            name='fecha_de_creacion',
        ),
        migrations.RemoveField(
            model_name='asignaturadocente',
            name='fecha_de_modificacion',
        ),
    ]
