# Generated by Django 4.2.1 on 2024-07-26 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0008_alter_area_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resolucion',
            name='fechadecarga',
        ),
    ]
