# Generated by Django 4.2.1 on 2024-08-09 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0009_remove_resolucion_fechadecarga'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignaturadocente',
            name='fecha_de_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
