# Generated by Django 4.2.1 on 2024-08-26 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0010_asignaturadocente_fecha_de_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='titulo',
            field=models.CharField(blank=True, null=True),
        ),
    ]
