version: '3'

services:
    application:
        container_name: adminitracion-departamentos
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./Dockerfile
        entrypoint: /home/app/entrypoint.sh
        expose:
            - 8000     
        environment:
            DJANGO_DEBUG=False
            DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
            DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
            DJANGO_DATABASE_URL=${DJANGO_DATABASE_URL}
            DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
            CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
            CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
