from .persona import PersonaViewSet 
from .jefe import JefeViewSet
from .departamento import DepartamentoViewSet
from .director import DirectorViewSet
from .docente import DocenteViewSet
from .noDocente import NoDocenteViewSet
from .resolucion import ResolucionViewSet
from .jefeDepartamento import JefeDepartamentoViewSet
from .area import AreaViewSet
from .asignatura import AsignaturaViewSet
from .asignaturaCarrera import AsignaturaCarreraViewSet
from .asignaturaDocente import AsignaturaDocenteViewSet
from .carrera import CarreraViewSet
from .directorCarrera import DirectorCarreraViewSet
from .tipoTitulo import TipoTituloViewSet
