from .persona import PersonaSerializer 
from .jefe import JefeSerializer
from .departamento import DepartamentoSerializer
from .director import DirectorSerializer
from .docente import DocenteSerializer
from .noDocente import NoDocenteSerializer
from .resolucion import ResolucionSerializer
from .jefeDepartamento import JefeDepartamentoSerializer,JefeDepartamentoCreateSerializer,JefeDepartamentoDetailSerializer
from .area import AreaSerializer
from .asignatura import AsignaturaSerializer
from .asignaturaCarrera import AsignaturaCarreraSerializer
from .asignaturaDocente import AsignaturaDocenteSerializer, AsignaturaDocenteCreateSerializer, AsignaturaDocenteDetailSerializer
from .carrera import CarreraSerializer
from .directorCarrera import DirectorCarreraSerializer
